import { SubjectSelection } from '../interfaces'

export const subjectData: SubjectSelection[] = [
    { code: 'INTG', text: 'Academic Integrity' },
    { code: 'ANTH', text: 'Anthropology' },
    { code: 'AQUA', text: 'Aquaculture' },
    { code: 'ARCH', text: 'Archaeology' },
    { code: 'ARTS', text: 'Arts' },
    { code: 'BIOC', text: 'Biochemistry' },
    { code: 'BIOL', text: 'Biology' },
    { code: 'BEAS', text: 'Boreal Ecosystems & Agri. Sci.' },
    { code: 'BSMG', text: 'Business & Org. Mgmt.' },
    { code: 'BUSN', text: 'Business Admin (Grenfell)' },
    { code: 'BUSI', text: 'Business Administration' },
    { code: 'CHEM', text: 'Chemistry' },
    { code: 'CIV', text: 'Civil Engineering' },
    { code: 'CLAS', text: 'Classics' },
    { code: 'CABE', text: 'Cognitive & Behaviour Ecology' },
    { code: 'CMSK', text: 'Communication Skills' },
    { code: 'CMST', text: 'Communication Studies' },
    { code: 'COMP', text: 'Computer Science' },
    { code: 'CPSK', text: 'Computer Skills' },
    { code: 'CRIM', text: 'Criminology' },
    { code: 'EASC', text: 'Earth Sciences' },
    { code: 'ECON', text: 'Economics' },
    { code: 'EFLC', text: 'Educ.&Francophone Lit. & Cult.' },
    { code: 'ED', text: 'Education' },
    { code: 'ECE', text: 'Electrical/Computer Engineer' },
    { code: 'ELTR', text: 'Electronics' },
    { code: 'ELTK', text: 'Electrotechnology' },
    { code: 'EMRE', text: 'Employment Relations' },
    { code: 'ENGI', text: 'Engineering' },
    { code: 'ENGR', text: 'Engineering Graphics' },
    { code: 'ENSY', text: 'Engineering Systems' },
    { code: 'ENGL', text: 'English' },
    { code: 'ENGS', text: 'English as a Second Language' },
    { code: 'ENSU', text: 'Environment and Sustainability' },
    { code: 'ENVP', text: 'Environmental Policy' },
    { code: 'ENVS', text: 'Environmental Science' },
    { code: 'ETMU', text: 'Ethnomusicology' },
    { code: 'FIRE', text: 'Fire Fighting' },
    { code: 'FISH', text: 'Fisheries Science' },
    { code: 'FLDS', text: 'Fluids' },
    { code: 'FOLK', text: 'Folklore' },
    { code: 'FDTE', text: 'Food Technology' },
    { code: 'FREN', text: 'French' },
    { code: 'GNDR', text: 'Gender Studies' },
    { code: 'GEOG', text: 'Geography' },
    { code: 'GERM', text: 'German' },
    { code: 'GRAD', text: 'Grad Studies' },
    { code: 'PHIA', text: 'Health Privacy Law Training' },
    { code: 'HIST', text: 'History' },
    { code: 'HKR', text: 'Human Kinetics and Recreation' },
    { code: 'HUMN', text: 'Humanities' },
    { code: 'CNTL', text: 'Instrumentation and Controls' },
    { code: 'INTE', text: 'Interdisciplinary' },
    { code: 'INTL', text: 'International' },
    { code: 'LANG', text: 'Language' },
    { code: 'LWSO', text: 'Law and Society' },
    { code: 'LEAD', text: 'Leadership' },
    { code: 'LING', text: 'Linguistics' },
    { code: 'MUN', text: 'MUN' },
    { code: 'BMRN', text: 'Marine Biology' },
    { code: 'MREK', text: 'Marine Eng. Knowledge' },
    { code: 'MENV', text: 'Marine Environment' },
    { code: 'MSTM', text: 'Maritime Stds/Tech Mgmt' },
    { code: 'MARI', text: 'Maritime Studies' },
    { code: 'MTPR', text: 'Materials and Processes' },
    { code: 'MATH', text: 'Mathematics' },
    { code: 'STAT', text: 'Mathematics - Statistics' },
    { code: 'ME', text: 'Mechanical Engineering' },
    { code: 'MECH', text: 'Mechanics' },
    { code: 'MED', text: 'Medicine' },
    { code: 'MST', text: 'Medieval Studies' },
    { code: 'MOBI', text: 'Mobility' },
    { code: 'MUS', text: 'Music' },
    { code: 'NASC', text: 'Nautical Science' },
    { code: 'NARC', text: 'Naval Architecture' },
    { code: 'NURS', text: 'Nursing' },
    { code: 'OHS', text: 'Occupational Health & Safety' },
    { code: 'OMAP', text: 'Ocean Mapping' },
    { code: 'OCSC', text: 'Ocean Sciences' },
    { code: 'OTEC', text: 'Ocean Technology' },
    { code: 'ONAE', text: 'Ocean/Naval Engineering' },
    { code: 'ONGR', text: 'Oceanography' },
    { code: 'ORTN', text: 'Orientation' },
    { code: 'PHAR', text: 'Pharmacy' },
    { code: 'PHIL', text: 'Philosophy' },
    { code: 'PHYS', text: 'Physics' },
    { code: 'POSC', text: 'Political Science' },
    { code: 'MIPG', text: 'Post Graduate Certificate' },
    { code: 'PROC', text: 'Process Engineering' },
    { code: 'PSYC', text: 'Psychology' },
    { code: 'RELS', text: 'Religious Studies' },
    { code: 'ROVO', text: 'Remotely Oper Vehicle Operator' },
    { code: 'RUSS', text: 'Russian' },
    { code: 'SFTY', text: 'Safety' },
    { code: 'SC', text: 'Science' },
    { code: 'CMSC', text: 'Scientific Computing' },
    { code: 'SCWK', text: 'Social Work' },
    { code: 'SCS', text: 'Social/Cultural Studies' },
    { code: 'SOCI', text: 'Sociology' },
    { code: 'SPAN', text: 'Spanish' },
    { code: 'TKPR', text: 'Technical Project' },
    { code: 'TECH', text: 'Technology' },
    { code: 'THEA', text: 'Theatre' },
    { code: 'THPH', text: 'Theoretical Physics' },
    { code: 'TRMO', text: 'Thermodynamics' },
    { code: 'TRSM', text: 'Tourism' },
    { code: 'TRSU', text: 'Transdisciplinary Sustain.' },
    { code: 'UGRD', text: 'Undergraduate Studies' },
    { code: 'UNIV', text: 'University' },
    { code: 'VART', text: 'Visual Arts' },
    { code: 'WKTM', text: 'Work Term' },
    { code: 'WKPR', text: 'Workshop Practice' },
]